#!/system/bin/sh

KERNEL_MODULE_DIR=/lib/modules
ROM_MODULE_DIR=/system/lib/modules

function makeWritable {
    mount -o remount,rw /system
}

function makeReadonly {
    mount -o remount,ro /system
}

cd $ROM_MODULE_DIR
for file in *.ko
do
    if [ -e $KERNEL_MODULE_DIR/$file ]
    then
        MD5SUM_ROM=`/system/xbin/md5sum $file | cut -d' ' -f1`
        MD5SUM_KERNEL=`/system/xbin/md5sum $KERNEL_MODULE_DIR/$file | cut -d' ' -f1`
        if [ $MD5SUM_ROM != $MD5SUM_KERNEL ]
        then
            #echo "Kernel module $file is different to kernel"
            makeWritable
            cp $KERNEL_MODULE_DIR/$file $file
            makeReadonly
        fi
    fi
done

