#!/system/bin/sh

# any kernel init configs go here

LOG_FILE=/data/local/init.scripts.log
if [ -e $LOG_FILE ]; then
    rm $LOG_FILE
fi

echo "Starting init.scripts.sh $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE

echo -n "Active govener:" | tee -a $LOG_FILE
GOVENOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo $GOVENOR | tee -a $LOG_FILE

# set governors

if [ $GOVENOR != "ondemand" ]; then
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
fi

sync 

echo "govenor" | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor | tee -a $LOG_FILE

echo "scaling_max_freq" | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq | tee -a $LOG_FILE

echo "scaling_min_freq" | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq | tee -a $LOG_FILE

GOVENER_DIR=/sys/devices/system/cpu/cpufreq/*/*
echo "govener settings" | tee -a $LOG_FILE
for GOVENOR_FILE in $GOVENER_DIR
do
    echo -n `basename $GOVENOR_FILE` ":" | tee -a $LOG_FILE
    cat $GOVENOR_FILE | tee -a $LOG_FILE
done

echo "Finished init.scripts.sh $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE
