#!/system/bin/sh

# any kernel init configs go here

LOG_FILE=/data/local/init.scripts.log
if [ -e $LOG_FILE ]; then
    rm $LOG_FILE
fi

echo "Starting init.scripts.sh $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE

echo -n "Active govener:" | tee -a $LOG_FILE
GOVENOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo $GOVENOR | tee -a $LOG_FILE

# need to enable all CPU cores in order to set them up
echo 4 > /sys/kernel/debug/tegra_mpdecision/conf/min_cpus
sleep 3
# set governors

if [ $GOVENOR != "ondemand" ]; then
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
fi

sync 

echo "govenor" | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor | tee -a $LOG_FILE

echo "scaling_max_freq" | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq | tee -a $LOG_FILE

echo "scaling_min_freq" | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq | tee -a $LOG_FILE
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq | tee -a $LOG_FILE

# reset core activation to default
echo 0 > /sys/kernel/debug/tegra_mpdecision/conf/min_cpus

if [ $GOVENOR = "ondemand" ]; then
# set ondemand prefs
echo "90" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo "3" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/ignore_nice_load
echo "10000000" > /sys/devices/system/cpu/cpufreq/ondemand/input_boost_duration
echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/powersave_bias
echo "4" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
echo "50000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
echo "340000" > /sys/devices/system/cpu/cpufreq/ondemand/two_phase_bottom_freq
echo "1000000" > /sys/devices/system/cpu/cpufreq/ondemand/two_phase_freq
echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/two_phase_dynamic
echo "5" > /sys/devices/system/cpu/cpufreq/ondemand/ui_counter
echo "30000" > /sys/devices/system/cpu/cpufreq/ondemand/ui_sampling_rate
echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/ux_boost_threshold
echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/ux_freq
echo "30" > /sys/devices/system/cpu/cpufreq/ondemand/ux_loading
echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy

else 

if [ $GOVENOR = "interactive" ]; then
# interactive prefs
echo "85" > /sys/devices/system/cpu/cpufreq/interactive/go_maxspeed_load
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/boost_factor
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/max_boost
echo "95" > /sys/devices/system/cpu/cpufreq/interactive/sustain_load
echo "30000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo "20000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/input_boost
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/boost
echo "20000" > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
echo "85" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
echo "1700000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/io_is_busy
fi
fi

GOVENER_DIR=/sys/devices/system/cpu/cpufreq/*/*
echo "govener settings" | tee -a $LOG_FILE
for GOVENOR_FILE in $GOVENER_DIR
do
    echo -n `basename $GOVENOR_FILE` ":" | tee -a $LOG_FILE
    cat $GOVENOR_FILE | tee -a $LOG_FILE
done

echo "Finished init.scripts.sh $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE
